[versions]
# Plugins
kotlin = "2.2.21"
android = "8.13.2"
binaryCompatibility = "0.18.1"
versionUpdater = "0.53.0"
ktlint = "14.0.1"
mavenRelease = "0.36.0"
moshiIR = "0.34.4"
ksp = "2.3.5"

# AndroidX libraries
compatLibrary = "1.7.1"
lifecycle = "2.9.2"
materialLibrary = "1.13.0"

# Third party Libraries
googleAdsId = "18.3.0"
huaweiAdsId = "3.4.26.303"
moshi = "1.15.2"
okhttp = "4.12.0"
pianoConsents = "1.0.0"
timber = "5.0.1"
viewBindingProperty = "1.5.9"

# Test Libraries
junit = "4.13.2"
androidxTestCore = "1.7.0"
mockitoKotlin = "6.2.3"
mockitoCore = "5.21.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
android-app = { id = "com.android.application", version.ref = "android" }
binaryCompatibility = {id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibility" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
mavenRelease = { id = "com.vanniktech.maven.publish", version.ref = "mavenRelease" }
moshiIR = { id = "dev.zacsweers.moshix", version.ref = "moshiIR"}
versionUpdater = { id = "com.github.ben-manes.versions", version.ref = "versionUpdater" }

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "compatLibrary" }
lifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle"}
material = { module = "com.google.android.material:material", version.ref = "materialLibrary" }
googleAdsId = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "googleAdsId" }
huaweiAdsId = { module = "com.huawei.hms:hms-ads-identifier", version.ref = "huaweiAdsId" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
pianoConsents = { module = "io.piano.android:consents", version.ref = "pianoConsents" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
viewBindingProperty = { module = "com.github.kirich1409:viewbindingpropertydelegate", version.ref = "viewBindingProperty" }

kotlinJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxTestCore = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
okhttpMockServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
